{
 "title": "Raccoon SIEM Collectors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "siem", "query": "label_values(job)" },
   {
    "name": "collector",
    "query": "label_values(up{job=\"$siem\", components=\"collectors\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "EPS Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_collector_eventsReceived{job=~\"$siem\",instance=~\"$collector\"}[1m])",
     "legendFormat": "EPS"
    }
   ]
  },
  {
   "title": "EPS Processing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_collector_eventsProcessed{job=~\"$siem\",instance=~\"$collector\"}[1m])",
     "legendFormat": "EPS"
    }
   ]
  },
  {
   "title": "EPS Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_eventsSent{job=~\"$siem\",instance=~\"$collector\"}[1m])) by (destination)",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "EPS Aggregated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_eventsAggregated{job=~\"$siem\",instance=~\"$collector\"}[1m])) by (rule)",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "EPS Filtered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_eventsFiltered{job=~\"$siem\",instance=~\"$collector\"}[1m])) by (filter)",
     "legendFormat": "{{filter}}"
    }
   ]
  },
  {
   "title": "Average Processing Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_collector_processingLatency_sum{job=\"$siem\",instance=~\"$collector\"}[1m]) / \nirate(raccoon_collector_processingLatency_count{job=\"$siem\",instance=~\"$collector\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$siem\",instance=~\"$collector\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Average GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(go_gc_duration_seconds_sum{job=\"$siem\",instance=~\"$collector\"}[1m]) /\nirate(go_gc_duration_seconds_count{job=\"$siem\",instance=~\"$collector\"}[1m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$siem\",instance=~\"$collector\"}",
     "legendFormat": "Goroutines"
    }
   ]
  }
 ]
}