{
 "title": "Raccoon SIEM Correlators",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "siem", "query": "label_values(job)" },
   {
    "name": "correlator",
    "query": "label_values(up{job=\"$siem\", components=\"correlators\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "EPS Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_correlator_eventsReceived{job=~\"$siem\",instance=~\"$correlator\"}[1m])",
     "legendFormat": "EPS"
    }
   ]
  },
  {
   "title": "EPS Correlated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_correlator_eventsCorrelated{job=~\"$siem\",instance=~\"$correlator\"}[1m])) by (rule)",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "EPS Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_correlator_eventsSent{job=~\"$siem\",instance=~\"$correlator\"}[1m])) by (destination)",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Average Processing Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_correlator_processingLatency_sum{job=\"$siem\",instance=~\"$correlator\"}[1m]) / \nirate(raccoon_correlator_processingLatency_count{job=\"$siem\",instance=~\"$correlator\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Average Output Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(raccoon_correlator_outputLatency_sum{job=\"$siem\",instance=~\"$correlator\"}[1m]) / \nirate(raccoon_correlator_outputLatency_count{job=\"$siem\",instance=~\"$correlator\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Average GC Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(go_gc_duration_seconds_sum{job=\"$siem\",instance=~\"$correlator\"}[1m]) /\nirate(go_gc_duration_seconds_count{job=\"$siem\",instance=~\"$correlator\"}[1m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$siem\",instance=~\"$correlator\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$siem\",instance=~\"$correlator\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"$siem\",instance=~\"$correlator\"}",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}