{
 "title": "Raccoon SIEM Collectors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "siem", "query": "label_values(job)" },
   {
    "name": "collector",
    "query": "label_values(up{job=\"$siem\", components=\"collectors\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "EPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_events{job=~\"$siem\",instance=~\"$collector\"}[1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "EPS by source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_events{job=~\"$siem\",instance=~\"$collector\"}[1m])) by (source, direction)",
     "legendFormat": "{{source}} -> {{direction}}"
    }
   ]
  },
  {
   "title": "EPS filtered out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_events_filtered{job=\"$siem\",instance=~\"$collector\"}[1m])) by (instance, source, filter)",
     "legendFormat": "{{source}} -> {{filter}}"
    }
   ]
  },
  {
   "title": "Aggregation Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(raccoon_collector_events_aggregated{job=\"$siem\", instance=~\"$collector\"}[1m])) by (source, rule)",
     "legendFormat": "{{source}} : {{rule}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"$siem\",instance=~\"$collector\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Average GC Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  go_gc_duration_seconds_sum{job=\"$siem\",instance=~\"$collector\"} / \n  go_gc_duration_seconds_count{job=\"$siem\",instance=~\"$collector\"}\n)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"$siem\",instance=~\"$collector\"})",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Average Processing Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  raccoon_collector_latency_total_sum{job=\"$siem\",instance=~\"$collector\"} / \n  raccoon_collector_latency_total_count{job=\"$siem\",instance=~\"$collector\"}\n)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Average Parsing Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  raccoon_collector_latency_parsing_sum{job=\"$siem\",instance=~\"$collector\"} / \n  raccoon_collector_latency_parsing_count{job=\"$siem\",instance=~\"$collector\"}\n) by (parser)",
     "legendFormat": "{{parser}}"
    }
   ]
  },
  {
   "title": "Average Serialization Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  raccoon_collector_latency_serialization_sum{job=\"$siem\",instance=~\"$collector\"} / \n  raccoon_collector_latency_serialization_count{job=\"$siem\",instance=~\"$collector\"}\n) by (destination)",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}