name: DDoS
window: 120
selectors:
  - tag: DDoS
    threshold: 2
    filter:
      sections:
        - conditions:
          - field: CorrelationRuleName
            op: =
            constant: DoS

identicalFields:
  - DestinationIPAddress
uniqueFields:
  - SourceIPAddress

triggers:
  firstTrigger:
    actions:
      - kind: release
        release:
          enrichment:
            - targetField: Incident
              constant: "true"
            - targetField: Message
              constant: DDoS attack detected
