name: DDoS
window: 1m
selectors:
  - tag: DDoS
    threshold: 2
    filter:
      sections:
        - conditions:
          - field: CorrelationRuleName
            op: =
            value: DoS

identicalFields:
  - DestinationIPAddress
uniqueFields:
  - SourceIPAddress

triggers:
  ft:
    actions:
      - kind: release
        release:
          mutate:
            - targetField: Incident
              constant: "true"
            - targetField: Message
              constant: DDoS attack detected
