name: DoS
window: 0

selectors:
  - tag: DoS
    threshold: 1
    filter:
      sections:
        - conditions:
          - field: Correlated
            op: =
            constant: false
          - field: OriginServiceName
            op: =
            constant: PeakFlow
          - field: Message
            op: =
            constant: DoS

identicalFields:
  - SourceIPAddress
  - DestinationIPAddress

triggers:
  firstTrigger:
    actions:
      - kind: release
        release:
          enrichment:
            - targetField: Message
              constant: DoS attack detected
