name: PigNikanor
# recovery correlation rule
kind: recovery
window: 1m
selectors:
  - tag: NikanorNasral
    threshold: 1
    filter:
      sections:
        - conditions:
            - field: Message
              op: =
              value: "я насрал"
            - field: RequestUser
              op: =
              value: "Никанор"
  - tag: NikanorUbral
      # это частичное событие позволит Никанору сохранить честь и достоинство
      recovery: true
      filter:
        sections:
          - conditions:
              - field: Message
                op: =
                value: "я убрал"
              - field: RequestUser
                op: =
                value: "Никанор"

identicalFields:
  - RequestUser

triggers:
  # timeout trigger
  to:
    actions:
      - kind: release
        release:
          mutate:
            - targetField: Incident
              constant: "true"
            - targetField: Message
              constant: "Ай, ай, ай, Никанор!"
